In [1]:
import numpy as np
from sklearn.metrics import mean_squared_error

In [2]:
%store -r X_train
%store -r X_test
%store -r y_train
%store -r y_test

In [3]:
# XGBooster

In [4]:
%store -r xgboost

In [5]:
xgboost_predict = xgboost.predict(X_test)
xgboost_predict

array([0.2107192 , 0.21790977, 0.22853848, ..., 0.22096965, 0.21561801,
       0.24658416], dtype=float32)

In [6]:
np.sqrt(mean_squared_error(y_test, xgboost_predict))

0.30696922559069595

In [7]:
# RandomForest

In [8]:
%store -r rf

In [9]:
rf.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [10]:
# Gradient Booster

In [11]:
from sklearn.metrics import classification_report

In [12]:
%store -r gb

In [14]:
print(classification_report(y_test,gb.predict(X_test)))

              precision    recall  f1-score   support

           0       0.92      1.00      0.96     93300
           1       0.71      0.00      0.00      8179

    accuracy                           0.92    101479
   macro avg       0.81      0.50      0.48    101479
weighted avg       0.90      0.92      0.88    101479



In [15]:
gb.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)